ComPWA/tensorwaves

.pylintrc
doc/conf.py
doc/requirements.txt
tox.ini

This commit remove the need to write redundant docstrings everywhere.

docs!: change documentation policy

---

.gitignore
.pre-commit-config.yaml
requirements-dev.txt
tensorwaves/interfaces.py
tox.ini

Closes https://github.com/ComPWA/tensorwaves/issues/33
See also https://github.com/ComPWA/tensorwaves/pull/47

ci: add mypy configuration and pre-commit hook

---

doc/conf.py
doc/requirements.txt
examples/jupyter/generate.ipynb

Fix the Sphinx error that Travis emits since https://github.com/ComPWA/tensorwaves/pull/74 (see [this Travis job](https://travis-ci.com/github/ComPWA/tensorwaves/jobs/351326126)).
- Failed job is **not** caused by [`sphinx-copybutton`](https://pypi.org/project/sphinx-copybutton/)
- Warning "`sphinx.util.inspect.Signature() is deprecated`" is emitted [when using Sphinx 3.1.1](https://travis-ci.com/github/ComPWA/tensorwaves/jobs/351376538#L664) instead of Sphinx 2.4.4
- "`WARNING: 'viewcode' reference target not found: _modules/tensorwaves/data/generate`" not fixed when setting `viewcode_follow_imported_members = False` (4e3d81b801503e1f59bf15f81eaf578eec276ccd)
- [`viewcode`](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) indeed causes the issue! …

ci: fix Sphinx linkcheck issues

---

requirements-dev.txt
tests/requirements.txt

Part 2 of #78 
This one doesn't fall under one of the points raised in #78, but I felt it necessary to keep in sync with the expertsystem.
Note that this also touches on #28

ci: set dev requirements to minimal

---

.pylintrc
.vscode/settings.json
tests/data/test_generate.py
tests/physics/helicityformalism/test_amplitude.py
tests/physics/helicityformalism/test_canonical.py
tests/physics/helicityformalism/test_helicityangles.py
tests/tox.ini
tox.ini

`pydocstyle` linting in vscode didn't work correctly, probably because of the `pydocstyle` args provided through `.vscode/settings.json`:
https://github.com/ComPWA/tensorwaves/blob/0c8c706f268d127c2ecfaeeb7b06cab22daf00b8/.vscode/settings.json#L26
This PR introduces another way to ignore docstrings in the tests folder that works for both linting from the terminal and in vscode.

ci: make pydocstyle work in vscode

---

setup.cfg
tensorwaves/physics/helicity_formalism/amplitude.py

Implements analytical continuation below threshold for the BreitWigner function. It uses the new amplitf two body momentum function to sidestep a lot of complex valued computations.

feat: add analytical continuation for Breit Wigner

---

environment.yml

Conda Forge is not needed, because the default channel already supplies Python and pip. In fact, conda-forge causes problems now, because it seems to default to Python 3.9 (which TF does not support).

fix: remove conda-forge from channels

---

.vscode/settings.json
tensorwaves/data/generate.py
tensorwaves/data/tf_phasespace.py
tests/data/test_tf_phasespace.py

fix: switch to tf.random.Generator

---

docs/conf.py
setup.cfg
tests/conftest.py

This fixes a bug in the canonical formalism. See [`expertsystem` release notes for 0.6.3](https://github.com/ComPWA/expertsystem/releases/tag/0.6.3).

build: upgrade to expertsystem 0.6.3

---

tests/data/test_generate.py

test: add test for generate_data

---

docs/conf.py

Fixes a small bug that is annoying when building the docs after cleaning the repo (e.g. using `git clean`).

fix: only determine doc version if available

---

src/tensorwaves/data/generate.py

Output e.g.
```
Generating phase space sample: 300875it [00:00, 303053.37it/s]                                                                                                                                   
Generating intensity-based sample: 30991it [00:12, 2397.30it/s]
```
Note that there is an overflow, because that's cut off after the generation
https://github.com/ComPWA/tensorwaves/blob/dd08dfdcceb26338d72a5076721a40b99983bbc1/src/tensorwaves/data/generate.py#L110

fix: correctly compute tqdm iterations

---

.editorconfig
.github/workflows/cd.yml
.github/workflows/ci.yml
.pre-commit-config.yaml
cspell.json
setup.cfg
tox.ini

- Removes the need to `npm`-install `markdownlint`.
- Upgrades `pre-commit`.
- Also did some alphabetical sorts in config files.

ci: implement markdownlint pre-commit hook

---

src/tensorwaves/physics/helicity_formalism/amplitude.py
tests/physics/helicity_formalism/test_amplitude.py

fix: throw invalid L error correctly

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

The issues templates still use the old issue labels. See also https://github.com/ComPWA/expertsystem/pull/420

ci: improve issue templates

---

tests/conftest.py
tests/optimizer/test_callbacks.py
tests/physics/helicity_formalism/test_kinematics.py

The doc CI for #192 fails because the shape of the data set that is returned by `HelicityKinematics.convert` is incorrect: its values contain floats, and should all be lists. This PR adds a test that checks the shape.

test: check shape of kinematics dataset

---

docs/usage/2_generate_data.ipynb
docs/usage/3_perform_fit.ipynb
reqs/3.6/requirements-dev.txt
reqs/3.6/requirements-doc.txt
reqs/3.6/requirements-sty.txt
reqs/3.6/requirements-test.txt
reqs/3.6/requirements.txt
reqs/3.7/requirements-dev.txt
reqs/3.7/requirements-doc.txt
reqs/3.7/requirements-sty.txt
reqs/3.7/requirements-test.txt
reqs/3.7/requirements.txt
reqs/3.8/requirements-dev.txt
reqs/3.8/requirements-doc.txt
reqs/3.8/requirements-sty.txt
reqs/3.8/requirements-test.txt
reqs/3.8/requirements.txt
setup.cfg
src/tensorwaves/estimator.py
src/tensorwaves/physics/helicity_formalism/amplitude.py
tests/conftest.py
tests/recipe/test_amplitude_creation.py
tests/test_estimator.py

The expertsystem was changed to not normalize the Intensity automatically anymore. To adapt to this change, the NLL estimator now gets another required argument, a phase space dataset. This is used to normalize the function.
Closes #191

refactor!: normalize function in NLL

---

cspell.json
docs/conf.py
reqs/3.6/requirements-doc.txt
reqs/3.7/requirements-doc.txt
reqs/3.8/requirements-doc.txt
reqs/requirements-dev.in
reqs/requirements-doc.in
tox.ini

See https://github.com/ComPWA/expertsystem/pull/452, but also the failing RTD builds
https://readthedocs.org/projects/tensorwaves/builds/12849097/

docs: remove module visualization

---

.github/workflows/linkcheck.yml
.github/workflows/release-drafter.yml
.github/workflows/requirements-cron.yml

See #205 #206 #207
While [dependabot](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates) is good at spotting security problems, it cannot (yet) upgrade our `pip` dependencies as granularly as the [requirements cron job](https://github.com/ComPWA/tensorwaves/actions?query=workflow%3A%22Requirements+%28scheduled%29%22) can do (namely through `pip-compile`). This adds the possibility of triggering the upgrade job manually.

ci: add GitHub Actions workflow dispatch

---

docs/usage/1_create_model.ipynb
docs/usage/2_generate_data.ipynb
docs/usage/3_perform_fit.ipynb

_Spin-off from #203_
This makes the notebooks a bit easier to maintain (especially when there are interface changes) and results in nicer formatting:
where for instance `optimize()` is generated with `` {meth}`.Minuit2.optimize` ``.
The drawback is that the notebooks don't look as nice anymore:

docs: switch to intersphinx links

---

tox.ini

_Extracted from #222_
This PR makes it possible to run notebooks through
```
EXECUTE_NB= tox -e doclive
```
so that you can work on the notebooks and directly see how their output is rendered on RTD. Some additional `--re-ignore` have been added, so that `sphinx-autobuild` won't be retriggered once the notebooks have been run the first time.

ci: allow running notebooks through tox doclive

---

cspell.json
docs/usage.ipynb
docs/usage/basics.ipynb

Added a new page `usage/basics` that shows how to generate data for 1D and 2D expressions without using the `expertsystem`. This illustrates what happens behind the scenes in `tensorwaves`.

docs: illustrate example without expertsystem

---

docs/usage.ipynb
docs/usage/basics.ipynb
docs/usage/step1.ipynb
docs/usage/step2.ipynb
docs/usage/step3.ipynb

Matplotlib and graphviz output is currently rendered as PNG, despite this:
https://github.com/ComPWA/tensorwaves/blob/7ad175fd0d7e486937f373255d3529fb374c69bd/docs/conf.py#L172-L184
Ideal would be to set `InlineBackend.figure_formats = ['svg']` by default through some IPython configuration, see e.g. https://stackoverflow.com/a/17582607/13219025 and https://ipython.readthedocs.io/en/stable/development/config.html, but I currently can't get these settings to affect Sphinx.

docs: render figures as SVG

---

reqs/3.6/requirements-dev.txt
reqs/3.6/requirements-doc.txt
reqs/3.6/requirements-extras.txt
reqs/3.6/requirements-sty.txt
reqs/3.6/requirements-test.txt
reqs/3.6/requirements.txt
reqs/3.7/requirements-dev.txt
reqs/3.7/requirements-doc.txt
reqs/3.7/requirements-extras.txt
reqs/3.7/requirements-sty.txt
reqs/3.7/requirements-test.txt
reqs/3.7/requirements.txt
reqs/3.8/requirements-dev.txt
reqs/3.8/requirements-doc.txt
reqs/3.8/requirements-extras.txt
reqs/3.8/requirements-sty.txt
reqs/3.8/requirements-test.txt
reqs/3.8/requirements.txt
setup.cfg
src/tensorwaves/model.py
src/tensorwaves/optimizer/minuit.py

Many thanks to @mayou36 for pointing out [`tf.experimental.numpy`](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy)!
Note: TF is currently the slowest of the backends for both optimizing and data generation. Could be that #100 offers a way out here and/or that we have to make the lambdifying a bit smarter.

feat: support lambdify to tensorflow

---

.pre-commit-config.yaml
.pre-commit-hooks/fix_first_nbcell.py
docs/usage.ipynb
docs/usage/basics.ipynb
docs/usage/step1.ipynb
docs/usage/step2.ipynb
docs/usage/step3.ipynb

Follow-up to #250. The cell magic conditionals didn't work well, which slowed down CI.

fix: avoid cell magic in colab cell

---

src/tensorwaves/optimizer/callbacks.py

Two fixes for the `YAMLSummary`:
- Scalar tensors are converted to built-in `complex` or `float`, so that they are rendered more nicely in the output of `YAMLSummary`.
- `YAMLSummary` now also dumps in `on_optimize_end()`, so that the `load_latest_parameters` indeed returns the latest parameters (see `test_callbacks.py`).
(Rebased on #251)

fix: improve output of YAMLSummary

---

src/tensorwaves/optimizer/callbacks.py
tests/conftest.py

The `csv.DictReader` crashes when there are complex values (and using `QUOTE_NONNUMERIC`). This was not spotted, because the tests only work with float parameters. Now one additional (complex) parameter is set free and the bug has been fixed. To speed up the tests, the UnbinnedNLL fixture uses Jax now.

fix: load complex parameter values from CSV

---

.github/workflows/ci-epic.yml
.github/workflows/ci.yml
src/tensorwaves/estimator.py
src/tensorwaves/model.py
tests/test_model.py

feat: add caching of constant sub expressions in SympyModels

---

.pylintrc
cspell.json
docs/usage.ipynb
docs/usage/basics.ipynb
docs/usage/step3.ipynb
src/tensorwaves/interfaces.py
src/tensorwaves/optimizer/minuit.py
src/tensorwaves/optimizer/scipy.py
tests/conftest.py
tests/optimizer/test_callbacks.py
tests/optimizer/test_minuit.py
tests/optimizer/test_scipy.py
tests/test_estimator.py

Wrapped the optimize `dict` output in a `FitResult` class. It's a rather simple `attr` data container that wraps what was previously in a `dict` form. Optimizer-specific info has been put under a `specifics` attribute.

refactor: wrap fit result in class

---

.github/workflows/ci.yml
src/tensorwaves/estimator.py

The changes introduced by #247 are a bit unstable. This PR makes caching optional, and disables it by default.

fix: make caching optional

---

docs/usage.ipynb
docs/usage/step2.ipynb
src/tensorwaves/data/transform.py

Simple fix: just casts [`ScalarSequence`](https://ampform.readthedocs.io/en/0.9.1/api/ampform.data.html#ampform.data.ScalarSequence) back into a `numpy` array so that a lambdified `Function` can handle it.

fix: support data generation with jax

---

docs/usage.ipynb
src/tensorwaves/estimator.py
tests/test_estimator.py

If the amplitude model is complicated, it can take over an hour to lambdify it to a `Model`. So it's annoying to have to do that twice if  you use the same backend for data generation and fitting. This PR allows reusing a `LambdifiedFunction` for fitting.

feat: allow constructing Estimator from Function

---

src/tensorwaves/data/__init__.py

Fixes the `tqdm` progress bar so that it gives a time estimate when calling `generate_phsp` and `generate_data`.

feat: provide time estimate data generation

---

docs/usage/step3.ipynb
src/tensorwaves/estimator.py
src/tensorwaves/interfaces.py
src/tensorwaves/model.py
src/tensorwaves/optimizer/_parameter.py
src/tensorwaves/optimizer/callbacks.py
src/tensorwaves/optimizer/minuit.py
src/tensorwaves/optimizer/scipy.py
tests/optimizer/test_minuit.py
tests/optimizer/test_scipy.py
tests/test_estimator.py
tests/test_interfaces.py

Closes #290 
- Added a method `FitResult.count_number_of_parameters()`
- Constructor arguments of `FitResult` are now validated. This is to ensure that functions and methods like `count_number_of_parameters()` keep working.
- All parameters in `FitResult` are now 'pretty printed' below each other, e.g.:
```python
FitResult(
minimum_valid=True,
execution_time=2.9841978549957275,
function_calls=166,
estimator_value=-7579.247627538372,
parameter_values={
'm_f(0)(980)': 0.989885368944097,
'Gamma_f(0)(980)': 0.060228379644260165,
},
parameter_errors={
'm_f(0)(980)': 0.0010628340144144574,
'Gamma_f(0)(980)': 0.0016523232241513362,
},
)
```
- AIC and BIC example provided in documentation.
- Using type alias `ParameterValue` where possible instead of `Union[...]`.

feat: implement FitResult.count_number_of_parameters

---

docs/usage/basics.ipynb
docs/usage/step3.ipynb
src/tensorwaves/interface.py
tests/test_interfaces.py
tests/test_model.py

Fix-up to #291, e.g.:
```python
FitResult.count_number_of_parameter(complex_twice=True)
```
See discussion here
https://app.reviewnb.com/ComPWA/tensorwaves/blob/main/docs/usage/step3.ipynb/#comment-19307800

refactor: rename real argument to complex_twice

---

docs/conf.py
docs/index.md
docs/tensorflow.txt
src/tensorwaves/model.py
src/tensorwaves/optimizer/callbacks.py
tox.ini

_See also https://github.com/ComPWA/ampform/pull/179_
* docs: pin more intersphinx pages
* fix: correct intersphinx links that were not previously checked
* fix: exclude version 'module' from API
* fix: move docstrings from __init__ to class definition
* refactor: get intersphinx version through function
* style: capitalize conf.py global vars that are no Sphinx options

docs: link to correct version on Binder/Colab

---

.pre-commit-config.yaml
docs/usage.ipynb
docs/usage/analytic-continuation.ipynb
docs/usage/basics.ipynb
docs/usage/faster-lambdify.ipynb
docs/usage/step1.ipynb
docs/usage/step2.ipynb
docs/usage/step3.ipynb

Launch buttons are missing on the website since #337. This is because `metadata.kernelspec` was removed.

fix: add back metadata.kernelspec to notebooks

---

.vscode/settings.json
src/tensorwaves/model/sympy.py

Closes #322
The role of `_backend_lambdify` and `_sympy_lambdify` is now swapped:
- `_backend_lambdify` is now purely a wrapper around `sympy.lambdify`.
- `_sympy_lambdify` offers a switch between `_backend_lambdify` and `optimized_lambdify`.
These functions will change further in #292, but this is PR focuses only on the problem describe din #322.

refactor: swap optimized_lambdify implementation

---

docs/usage/faster-lambdify.ipynb
src/tensorwaves/model/sympy.py
tests/unit/model/test_sympy.py

Additional fixes:
- The faster-lambdify notebook was failing due to the interface change introduced by #348. This was not noticed, because the `%%time` statement in the cell makes the error code of that cell return 'success'. The error has been fixed and a hidden test cell has been added to prevent such failures in the future.
- `optimized_lambdify` now directly calls `_backend_lambdify` is `max_complexity` is higher than the number of nodes in the expression.

test: add unit tests for optimized_lambdify

---

tests/integration/ampform/conftest.py
tests/integration/ampform/test_callbacks.py

Integration tests have become unstable since #349, see e.g. https://github.com/ComPWA/tensorwaves/actions/runs/1504632721, because the callback output is written to the same file when using `optimized_lambdify` / `_backend_lambdify`.

fix: write callback output to separate files

---

docs/usage/step3.ipynb
src/tensorwaves/interface.py

Added links to the 'fit result' objects in the `iminuit` and SciPy APIs.

docs: add API links to FitResult.specifics

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
docs/usage/step3.ipynb
pytest.ini
setup.cfg
src/tensorwaves/function/__init__.py
tox.ini

Switch from [`pytest-notebook`](https://pypi.org/project/pytest-notebook) to [`nbmake`](https://pypi.org/project/nbmake). Now it's again possible to run specific notebooks from the terminal with e.g.:
```shell
pytest --nbmake docs/usage/basics.ipynb
```
Other small fixes:
- Avoid `fast_lambdify()` in Jupyter notebooks to speed up docs workflow.
- Cast to `tuple` in `ParametrizedBackendFunction`.

ci: switch to nbmake

---

docs/usage/step3.ipynb
src/tensorwaves/_backend.py
src/tensorwaves/function/sympy.py
tests/unit/function/test_sympy.py

#348 introduced a bug: the recombined function was not JIT-compiled, which significantly slowed down performance. This was temporarily avoided in #359.
| GitHub Action | b920c77 (no JIT) | 80e542c (with JIT) |
| --- | --- | --- |
| ci-docs | [9m 6s](https://github.com/ComPWA/tensorwaves/actions/runs/1526379716) | [7m 21s](https://github.com/ComPWA/tensorwaves/actions/runs/1526435002) |
| pytest-cov | [2m 10s](https://github.com/ComPWA/tensorwaves/runs/4383088855?check_suite_focus=true) | [1m 20s](https://github.com/ComPWA/tensorwaves/runs/4383253350?check_suite_focus=true) |

fix: jit-compile recombined fast_lambdify function

---

docs/abbreviate_signature.py
src/tensorwaves/data/__init__.py
src/tensorwaves/data/phasespace.py
src/tensorwaves/data/transform.py
src/tensorwaves/optimizer/callbacks.py
src/tensorwaves/optimizer/scipy.py
tests/unit/test_backend.py
tox.ini

Import expensive modules inline to speed up importing `tensorwaves`. This makes `import tensorwaves` (and collecting tests) about 8x as fast. Profiling done with [tuna](https://github.com/nschloe/tuna) as follows (see [stackoverflow](https://stackoverflow.com/a/51300944)):
```shell
python3 -X importtime -c "import tensorwaves" 2> tw.log && tuna tw.log
```

feat: speed up imports

---

pytest.ini
setup.cfg
src/tensorwaves/interface.py
src/tensorwaves/optimizer/callbacks.py
src/tensorwaves/optimizer/minuit.py
src/tensorwaves/optimizer/scipy.py
tests/unit/optimizer/test_minuit.py

Previously, if no callback was specified in the optimizer constructor, an empty CallbackList would be created and on_optimize_end etc were always called. This is (theoretically) slower.
Some other improvements:
- Use [`attrs` next-generation API](https://www.attrs.org/en/stable/api.html#next-gen) (see also https://github.com/ComPWA/compwa-org/issues/90).
- Avoid creating stream on creation of Loadable callback.
- Fail pytest on warnings (this helped fishing out the above bug)

ci: avoid callbacks if unspecified

---

.github/workflows/ci-tests.yml
benchmarks/ampform.py
pytest.ini
tests/conftest.py
tests/data/test_generate.py
tests/data/test_phasespace.py
tox.ini

Import expensive modules in the tests inline so that `pytest --collect-only` is faster.

ci: speed up pytest collect

---

src/tensorwaves/function/sympy.py
tests/function/test_sympy.py

See cse argument in
https://docs.sympy.org/latest/modules/utilities/lambdify.html#sympy.utilities.lambdify.lambdify
This might fix https://github.com/ComPWA/tensorwaves/pull/345#commitcomment-61398587

feat: lambdify with common sub-expressions

---

docs/usage/basics.ipynb
docs/usage/step3.ipynb
src/tensorwaves/data/__init__.py
src/tensorwaves/data/transform.py
src/tensorwaves/estimator.py
src/tensorwaves/function/__init__.py
src/tensorwaves/function/sympy/__init__.py
tests/function/test_function.py
tests/test_estimator.py

Closes #323 
- Added a convenience function `tensorwaves.function.get_source_code()`
- Added read-only properties `function` and `argument_order` to `ParametrizedBackendFunction` (parallels `attrs`-decorated `PositionalArgumentFunction` class).
- `PositionalArgumentFunction` is now used internally in `ParametrizedBackendFunction` (simplifies its `__call__()` method).
- Symbols are not force-dummified anymore if `use_cse=False`

feat: implement get_source_code function

---

docs/install.md
setup.cfg

AmpForm is not part of the interface and source code implementation anymore and only required when TensorWaves is used for PWA. Install with:
```shell
pip install tensorwaves[pwa]
```

build: make ampform an optional dependency

---

src/tensorwaves/data/transform.py
src/tensorwaves/function/__init__.py
src/tensorwaves/function/sympy/_printer.py
src/tensorwaves/interface.py
src/tensorwaves/optimizer/__init__.py
tests/function/test_function.py

- Wrote some additional tests for the `tensorwaves.function` module
- [`TYPE_CHECKING`](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) is now [ignored](https://coverage.readthedocs.io/en/latest/excluding.html#excluding-code-from-coverage-py) in test coverage

test: increase test coverage

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
.github/workflows/benchmark.yml
.github/workflows/ci-tests.yml
.pre-commit-config.yaml
docs/install.md
pytest.ini
setup.cfg
src/tensorwaves/data/phasespace.py
src/tensorwaves/data/rng.py
src/tensorwaves/estimator.py
src/tensorwaves/function/_backend.py
src/tensorwaves/function/sympy/__init__.py
src/tensorwaves/optimizer/callbacks.py
src/tensorwaves/optimizer/scipy.py
tests/data/test_rng.py
tests/function/test_backend.py
tests/optimizer/test_fit_simple_model.py
tox.ini

All computational backends are now optional dependencies (apart from NumPy). So for instance, to install TensorWaves with JAX, run:
```shell
pip install tensorwaves[jax]
```
To do amplitude analysis, install with:
```shell
pip install tensorwaves[jax,pwa]
```

build: make tensorflow an optional dependency

---

.cspell.json
src/tensorwaves/data/__init__.py
src/tensorwaves/data/_data_sample.py
src/tensorwaves/data/phasespace.py
tests/data/test_data.py

Closes #395 
```python
import ampform
import qrules
from ampform.dynamics.builder import create_relativistic_breit_wigner_with_ff
from tensorwaves.data import (
IntensityDistributionGenerator,
TFPhaseSpaceGenerator,
TFUniformRealNumberGenerator,
)
from tensorwaves.data.transform import SympyDataTransformer
from tensorwaves.function.sympy import create_parametrized_function
reaction = qrules.generate_transitions(
initial_state="J/psi(1S)",
final_state=["gamma", "pi0", "pi0"],
allowed_intermediate_particles=["f(0)"],
allowed_interaction_types=["strong", "EM"],
)
builder = ampform.get_builder(reaction)
resonances = reaction.get_intermediate_particles()
for p in resonances:
builder.set_dynamics(p.name, create_relativistic_breit_wigner_with_ff)
model = builder.formulate()
intensity = …
```

fix: hide progress bar of domain generator

---

docs/amplitude-analysis.ipynb
docs/usage/basics.ipynb
src/tensorwaves/optimizer/minuit.py
tests/optimizer/test_fit_simple_model.py

This makes it possible to access [`iminuit.Minuit`](https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit)'s methods and attributes before calling `optimize()`.

feat: add minuit_modifier constructor argument

---

docs/usage/basics.ipynb
src/tensorwaves/optimizer/callbacks.py

Also fixes a small bug: callbacks that write to disk skip writing when computing the Hesse.
Preview [here](https://tensorwaves--401.org.readthedocs.build/en/401/usage/basics.html#minuit2).

docs: illustrate Hesse from FitResult.specifics

---

.cspell.json
docs/amplitude-analysis.ipynb
docs/usage/caching.ipynb
docs/usage/faster-lambdify.ipynb
src/tensorwaves/estimator.py
src/tensorwaves/function/sympy/__init__.py

Previously, [`prepare_caching()`](https://tensorwaves.readthedocs.io/en/0.4.1/api/tensorwaves.function.sympy.html#tensorwaves.function.sympy.prepare_caching) (which is used by [`create_cached_function()`](https://tensorwaves.readthedocs.io/en/0.4.1/api/tensorwaves.function.sympy.html#tensorwaves.estimator.create_cached_function)) substituted fixed parameter values with [`subs()`](https://docs.sympy.org/latest/modules/core.html#sympy.core.basic.Basic.subs), which can be slow in case of larger expressions. The function now uses [`xreplace()`](https://docs.sympy.org/latest/modules/core.html#sympy.core.basic.Basic.xreplace) instead.
Also improved the docstrings of both functions, preview [here](https://tensorwaves--403.org.readthedocs.build/en/403/api/tensorwaves.estimator.html#tensorwaves.est …

fix: use xreplace in prepare_caching()

---

docs/conf.py

Links to `graphviz`'s API are now also embedded correctly. Follow-up to #405.

docs: show second level in left sidebar

---

.github/workflows/ci-tests.yml
docs/conf.py

Adds a [`workflow_dispatch` with inputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs) that allows running all tests manually with the latest version of AmpForm installed.

ci: manually run tests with latest AmpForm version

---

docs/install.md

Rewrote the installation page a bit so that it's clearer how to pin all dependencies with Conda. Preview [here](https://tensorwaves--411.org.readthedocs.build/en/411/install.html).

docs: clarify pinned dependencies with Conda

---

.cspell.json
docs/amplitude-analysis.ipynb

Added an example of how to use [`create_cached_function()`](https://tensorwaves--412.org.readthedocs.build/en/412/api/tensorwaves.estimator.html#tensorwaves.estimator.create_cached_function) in combination with an [`Estimator`](https://tensorwaves--412.org.readthedocs.build/en/412/api/tensorwaves.estimator.html#tensorwaves.estimator.Estimator). Preview [here](https://tensorwaves--412.org.readthedocs.build/en/412/amplitude-analysis.html#simplified-procedure-create-cached-function).

docs: use create_cached_function() in PWA notebook

---

docs/install.md

Added an additional install example that shows how to install a specific branch or tag with `pip` from Git _with optional dependencies_. Preview [here](https://tensorwaves--413.org.readthedocs.build/en/413/install.html#quick-installation).

docs: show how to install from git with opt. deps

---

docs/conf.py
src/tensorwaves/estimator.py

If feeding a `DataSample` as `domain` without weights, the size of the array previously became equal to the number of keys in the `DataSample`, whereas it should be the `len` of each of its arrays. This PR fixes that bug by computing the size from the `observed_y`, which is one-dimensional anyway.

fix: compute default weights from observed values

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
.cspell.json
.pre-commit-config.yaml
.prettierignore
.vscode/settings.json
pytest.ini
setup.cfg

- TensorWaves can now be installed with [AmpForm v0.14.0](https://github.com/ComPWA/ampform/releases/tag/0.14.0).
- Also removed [`pip-tools`](https://github.com/jazzband/pip-tools), since upgrading is now handled purely by [`update-pip-constraints`](https://github.com/ComPWA/update-pip-constraints).
- Fixed [this problem](https://github.com/ComPWA/tensorwaves/runs/5873479487?check_suite_focus=true#step:8:36) with pytest for notebooks.

build: allow installing AmpForm v0.14.x

---

docs/amplitude-analysis/analytic-continuation.ipynb

Preview [here]().
Switched to [`PhaseSpaceFactorSWave`](https://ampform.readthedocs.io/en/0.14.0/api/ampform.dynamics.phasespace.html#ampform.dynamics.phasespace.PhaseSpaceFactorSWave). See comparison with normal phase space factor [here](https://ampform.readthedocs.io/en/0.14.0/usage/dynamics.html#analytic-continuation).

docs: use Chew-Mandelstam in analytic continuation

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
.github/release-drafter.yml
.pre-commit-config.yaml
setup.cfg

Should have been done in #424, so that there is no need to make a new TensorWaves once AmpForm is updated. With the currentl design, AmpForm and TensorWaves are separated enough that the releases don't need to be tunded.
---
Also simplifies the release notes through https://github.com/ComPWA/repo-maintenance/issues/55.

build: remove version limit from AmpForm

---

.github/release-drafter.yml
pytest.ini
src/tensorwaves/data/transform.py
src/tensorwaves/function/sympy/__init__.py
tests/function/test_sympy.py

Previously, it was not possible to lambdify SymPy expressions that contain [`sympy.Indexed`](https://docs.sympy.org/latest/modules/tensor/indexed.html#sympy.tensor.indexed.Indexed) symbols (see [TR-008](https://compwa-org.readthedocs.io/report/008.html)). This PR makes it possible to use such expressions with [`create_function()`]() and related functions.

feat: lambdify Sympy.indexed expressions

---

.cspell.json
.flake8
docs/conf.py
docs/index.md
docs/usage/basics.ipynb
pytest.ini
src/tensorwaves/function/__init__.py
src/tensorwaves/function/sympy/__init__.py
src/tensorwaves/interface.py

- Added docstrings to `create_function()` and `create_parametrized_function()`
- `__eq__()` and `__call__()` methods are now hidden from the API by default

docs: improve docstrings of `function` module

---

docs/usage/basics.ipynb
src/tensorwaves/optimizer/callbacks.py
uv.lock

In reproducible fits (e.g. https://github.com/ComPWA/PWA-JPsi2pbarSigmaKS/pull/121), it can be useful to commit the fit result file. By setting `git_friendly=True` in `YAMLSummary`, entries that are not stable during a reproducible fit (like `time`) are omitted from the written YAML file.

FEAT: implement `git_friendly` flag for `YAMLSummary` callback

---

.pre-commit-config.yaml
benchmarks/ampform.py
docs/usage/faster-lambdify.ipynb
pyproject.toml
src/tensorwaves/data/transform.py
src/tensorwaves/estimator.py
src/tensorwaves/function/_backend.py
src/tensorwaves/function/sympy/__init__.py
src/tensorwaves/optimizer/minuit.py
tests/function/test_sympy.py
uv.lock

Added a `use_jit` flag to functions like [`create_function()`](https://tensorwaves.readthedocs.io/0.4.13/api/tensorwaves.function.sympy/#tensorwaves.function.sympy.create_function). The default behaviour is kept (`use_jit=None`), but it is now possible to avoid JIT compilation by setting `use_jit=False`.

FEAT: implement `use_jit` flag for lambdifier functions

---

.pre-commit-config.yaml
pyproject.toml
uv.lock

Closes https://github.com/ComPWA/policy/issues/421
With [TensorFlow v2.20.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.20.0), Python 3.13 is now well-supported.

ENH: run test suite over Python 3.13
