ComPWA/tensorwaves

- CONTRIBUTING.md
- README.md
Requires  https://github.com/ComPWA/tensorwaves/pull/4 and https://github.com/ComPWA/tensorwaves/pull/5
> docs: add README and CONTRIBUTE

- .gitignore
- .travis.yml
- README.md
- setup.py
- tensorwaves/expertsystem/ui/default_settings.py
- tensorwaves/expertsystem/ui/system_control.py
- tensorwaves/physics/__init__.py
- tensorwaves/physics/helicityformalism/__init__.py
- tests/pytest.ini
Closes https://github.com/ComPWA/tensorwaves/issues/19
Closes https://github.com/ComPWA/tensorwaves/issues/24
> ci: add travis CI

- .pylintrc
- tensorwaves/interfaces.py
- tox.ini
Closes https://github.com/ComPWA/tensorwaves/issues/18
Defines the basic interfaces for the interaction of the main modules of
tensorwaves:
* Intensity/Function
* Estimator
* Data
* Optimizer
Note that the interfaces are inspired by ComPWA.
https://github.com/ComPWA/ComPWA
> feat: add interfaces

- .pylintrc
- tox.ini
> ci: ignore missing docstring init and method

- .travis.yml
- environment.yml
- setup.py
> build: drop Python 3.5 support

- .editorconfig
- .pre-commit-config.yaml
- .pylintrc
- doc/contribute.rst
- pyproject.toml
- requirements-dev.txt
- tox.ini
This is a proposal presented as a PR (instead of an issue) as to be able to directly see the effect. The formatting is also tested in Travis CI.
See also https://github.com/ComPWA/pycompwa/pull/91
> style: add black formatting configuration

- doc/conf.py
- doc/requirements.txt
- doc/tensorflow.txt
Adds a sphinx object inventory for tensorflow related objects which can then nicely be linked to the tensorflow documentation via intersphinx.
> docs: add tensorflow sphinx object inventory

- tensorwaves/physics/helicityformalism/amplitude.py
Closes #2
This will be improved further with #44
> refactor: improve amplitude building code

- codecov.yml
- doc/conf.py
- examples/intensity-recipe.yaml
- examples/test.py
- requirements.txt
- tensorwaves/data/__init__.py
- tensorwaves/data/generate.py
- tensorwaves/data/tf_phasespace.py
- tensorwaves/interfaces.py
- tensorwaves/physics/__init__.py
- tensorwaves/physics/helicityformalism/amplitude.py
- tensorwaves/physics/helicityformalism/kinematics.py
- tensorwaves/physics/particle.py
- tests/data/test_generate.py
- tests/physics/helicityformalism/test_helicityangles.py
- tox.ini
We might have to improve the generate interface slightly. This is currently ported 1 to 1 from ComPWA.
> feat: add data generation functionality

- examples/intensity-recipe.yaml
- tensorwaves/physics/helicityformalism/amplitude.py
- tests/physics/helicityformalism/test_amplitude.py
- tox.ini
> refactor: improve modularity of helicity formalism amplitudes

- doc/contribute.rst
- examples/intensity-recipe.yaml
- requirements.txt
- tensorwaves/physics/helicityformalism/amplitude.py
- tensorwaves/physics/helicityformalism/kinematics.py
> feat: add Blatt-Weisskopf barrier factor option

- tensorwaves/physics/helicityformalism/amplitude.py
> refactor: switch to typing.NamedTuple

- .gitignore
- .vscode/.gitignore
- .vscode/settings.json
- doc/contribute.rst
Part 1 of #78 
For the prior discussion, see https://github.com/ComPWA/expertsystem/pull/41
> ci: standardize VSCode settings

- .pre-commit-config.yaml
- .travis.yml
- .vscode/settings.json
- doc/conf.py
- examples/python/workflow.py
- requirements-dev.txt
- setup.py
- tensorwaves/__init__.py
- tensorwaves/data/__init__.py
- tensorwaves/data/generate.py
- tensorwaves/estimator.py
- tensorwaves/interfaces.py
- tensorwaves/optimizer/__init__.py
- tensorwaves/physics/__init__.py
- tensorwaves/physics/helicityformalism/__init__.py
- tensorwaves/physics/helicityformalism/amplitude.py
- tensorwaves/physics/helicityformalism/kinematics.py
- tox.ini
Part 3 of #78 
See also https://github.com/ComPWA/expertsystem/pull/28
> ci!: add and enforce pydocstyle check

- .travis.yml
- examples/python/workflow.py
- requirements-dev.txt
- tox.ini
> ci!: enforce flake8 through Travis

- .pre-commit-config.yaml
- .travis.yml
- .vscode/settings.json
- setup.py
- tensorwaves/data/generate.py
- tensorwaves/interfaces.py
- tensorwaves/physics/helicityformalism/kinematics.py
- tests/__init__.py
- tests/data/__init__.py
- tests/physics/__init__.py
- tests/physics/helicityformalism/__init__.py
- tox.ini
Part 5 of #78 
Closes https://github.com/ComPWA/tensorwaves/issues/54
> ci!: enforce mypy check through Travis

- .pre-commit-config.yaml
- .pylintrc
- .travis.yml
- examples/python/workflow.py
- tensorwaves/physics/helicityformalism/amplitude.py
- tests/physics/helicityformalism/test_amplitude.py
- tox.ini
Part 6 of #78 
Required some refactoring because of `too-many-locals`
> ci!: enforce pylint check through Travis

- .pre-commit-config.yaml
- .travis.yml
- doc/contribute.rst
> ci: enforce pre-commit checks through Travis

- .pre-commit-config.yaml
- .vscode/settings.json
- doc/install/install.rst
- doc/install/virtual-environment.rst
- requirements-dev.txt
Part 8 of #78
Can define rstcheck configuration later on in a setup.cfg file
in case there are undefined roles etc, see:
https://github.com/myint/rstcheck#configuration-file
> ci!: add and enforce rstcheck

- .pre-commit-config.yaml
- .prettierrc
- .vscode/settings.json
- README.md
- doc/_templates/genindex.html
- doc/_templates/layout.html
> ci!: add and enforce Prettier formatting

- .gitignore
- .pre-commit-config.yaml
- README.md
- doc/contribute.rst
- doc/index.rst
- doc/requirements.txt
- requirements-dev.txt
- tests/requirements.txt
- tox.ini
> ci!: set up tox test environments

- examples/workflow/2_generate_data.ipynb
> docs: let generate data notebook use Step 1

- README.md
- doc/contribute.rst
- doc/index.rst
- doc/install.rst
- tox.ini
> docs: add section on RTD PR build

- doc/conf.py
- doc/contribute.rst
- examples/workflow/.gitignore
- examples/workflow/1_create_model.ipynb
- examples/workflow/2_generate_data.ipynb
- examples/workflow/3_perform_fit.ipynb
Closes #68 
This PR resulted in #99
> docs: write "Step 3: Perform fit"

- doc/install.rst
- examples/workflow/1_create_model.ipynb
- examples/workflow/3_perform_fit.ipynb
- setup.cfg
* Also some smaller fixes to the documentation
* **Bumps to version `0.0.0a0`**
* Removes 'no PyPI package banner
> docs: add note about fixing parameters

- README.md
- doc/index.rst
- setup.cfg
> docs: serve notebooks on Binder

- tensorwaves/physics/helicity_formalism/amplitude.py
Addresses #118, but does not close it. Since #116, dynamics are not provided from the recipe file, so we need some default.
> feat: add default dynamics RelativisticBW

- .github/workflows/ci.yml
- .gitignore
- doc/conf.py
- environment.yml
- examples/intensity-recipe.yaml
- examples/workflow/1_create_model.ipynb
- examples/workflow/2_generate_data.ipynb
- examples/workflow/3_perform_fit.ipynb
- pyproject.toml
- setup.cfg
- tensorwaves/data/tf_phasespace.py
- tensorwaves/physics/helicity_formalism/amplitude.py
> build!: upgrade to TF2.3

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- doc/contribute.rst
See https://github.com/ComPWA/expertsystem/pull/238
> ci!: automate release notes

- doc/conf.py
- examples/workflow/1_create_model.ipynb
- setup.cfg
- tests/conftest.py
See
https://github.com/ComPWA/expertsystem/releases/tag/0.6.0
for the changes
> build: upgrade to expertsystem 0.6.0

- .github/workflows/ci-epic.yml
See https://github.com/ComPWA/expertsystem/pull/374
> ci: add GitHub workflow for epic branches

- .github/workflows/cd.yml
- pyproject.toml
See https://github.com/ComPWA/expertsystem/issues/377
> ci: build wheel and fix GitHub deploy

- .gitignore
- docs/conf.py
- docs/usage/3_perform_fit.ipynb
- src/tensorwaves/optimizer/logging.py
- src/tensorwaves/optimizer/minuit.py
Adds a tf file logging decorator that can be used in Optimizers to add log variables. The decorator wraps a model updating function.
Note its some preliminary code that shows what I had in mind with the decorator. You can see it in action by calling tensorboard like this
```sh
tensorboard --logdir logs
```
> feat: add variable logging functionality using tf

- src/tensorwaves/optimizer/minuit.py
> feat: print execute time in optimize

- .github/release-drafter.yml
- .github/workflows/pr-linting.yml
- .github/workflows/requirements-cron.yml
- labels.toml
See https://github.com/ComPWA/expertsystem/pull/422 and https://github.com/ComPWA/expertsystem/pull/423
> ci: add issue label for interface changes

- .github/workflows/ci.yml
- .github/workflows/linkcheck.yml
- .github/workflows/requirements-pr.yml
See https://github.com/ComPWA/expertsystem/pull/455
> ci: run CI on draft PR

- docs/conf.py
- reqs/3.6/requirements-dev.txt
- reqs/3.6/requirements-doc.txt
- reqs/3.6/requirements-sty.txt
- reqs/3.6/requirements-test.txt
- reqs/3.6/requirements.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.7/requirements-doc.txt
- reqs/3.7/requirements-sty.txt
- reqs/3.7/requirements-test.txt
- reqs/3.7/requirements.txt
- reqs/3.8/requirements-dev.txt
- reqs/3.8/requirements-doc.txt
- reqs/3.8/requirements-sty.txt
- reqs/3.8/requirements-test.txt
- reqs/3.8/requirements.txt
- setup.cfg
- src/tensorwaves/optimizer/minuit.py
> build: upgrade to iminuit v2.x

- docs/_templates/module.rst_t
- docs/_templates/package.rst_t
See https://github.com/ComPWA/expertsystem/pull/495
> docs: render module import line on API pages

- docs/usage/1_create_model.ipynb
- docs/usage/2_generate_data.ipynb
- docs/usage/3_perform_fit.ipynb
- reqs/3.6/requirements-dev.txt
- reqs/3.6/requirements-doc.txt
- reqs/3.6/requirements-sty.txt
- reqs/3.6/requirements-test.txt
- reqs/3.6/requirements.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.7/requirements-doc.txt
- reqs/3.7/requirements-sty.txt
- reqs/3.7/requirements-test.txt
- reqs/3.7/requirements.txt
- reqs/3.8/requirements-dev.txt
- reqs/3.8/requirements-doc.txt
- reqs/3.8/requirements-sty.txt
- reqs/3.8/requirements-test.txt
- reqs/3.8/requirements.txt
- setup.cfg
- src/tensorwaves/data/generate.py
- src/tensorwaves/optimizer/minuit.py
See https://github.com/ComPWA/expertsystem/pull/508
> fix: use tqdm.autonotebook

- .vscode/settings.json
- docs/conf.py
- docs/usage/1_create_model.ipynb
- docs/usage/2_generate_data.ipynb
- docs/usage/3_perform_fit.ipynb
- reqs/3.6/requirements-dev.txt
- reqs/3.6/requirements-doc.txt
- reqs/3.6/requirements-sty.txt
- reqs/3.6/requirements-test.txt
- reqs/3.6/requirements.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.7/requirements-doc.txt
- reqs/3.7/requirements-sty.txt
- reqs/3.7/requirements-test.txt
- reqs/3.7/requirements.txt
- reqs/3.8/requirements-dev.txt
- reqs/3.8/requirements-doc.txt
- reqs/3.8/requirements-sty.txt
- reqs/3.8/requirements-test.txt
- reqs/3.8/requirements.txt
- setup.cfg
- src/tensorwaves/physics/helicity_formalism/amplitude.py
- tests/physics/helicity_formalism/TestD1ToD0PiPi.yml
- tests/physics/helicity_formalism/TestEpemToDmD0Pip.yml
- tests/physics/helicity_formalism/test_angular_distributions.py
- tests/physics/helicity_formalism/test_kinematics.py
This is in preparation for the final release before the switch to SymPy (see #222)
> build: upgrade to expertsystem 0.6.10

- reqs/3.6/requirements-dev.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.8/requirements-dev.txt
- reqs/requirements-dev.in
See https://github.com/ComPWA/expertsystem/pull/502
> ci: add collapsible_headings labextension

- .pre-commit-config.yaml
- .pre-commit-hooks/fix_first_nbcell.py
- .pre-commit-hooks/fix_nbformat_version.py
- docs/usage.ipynb
- docs/usage/basics.ipynb
- docs/usage/step1.ipynb
- docs/usage/step2.ipynb
- docs/usage/step3.ipynb
See https://github.com/ComPWA/expertsystem/pull/535
> docs: add install cells for Google Colab

- .github/release-drafter.yml
- docs/index.md
See https://github.com/ComPWA/expertsystem/pull/538 and https://github.com/ComPWA/expertsystem/pull/539
> ci: add PR message to release notes

- docs/usage.ipynb
- docs/usage/step1.ipynb
- docs/usage/step3.ipynb
- src/tensorwaves/data/phasespace.py
- tests/conftest.py
In preparation of upgrade to [AmpForm v0.10.0](https://github.com/ComPWA/ampform/milestone/7) (see https://github.com/ComPWA/ampform/pull/84). See also https://github.com/ComPWA/qrules/pull/66.
> style: import qrules as qrules

- docs/usage/step2.ipynb
Show how to generate a deterministic data and phase space sample in step 2 of the documentation.
> docs: generate deterministic sample in step 2

- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- docs/conf.py
- setup.cfg
See AmpForm [v0.11.0](https://github.com/ComPWA/ampform/releases/tag/0.11.0) and [v0.11.1](https://github.com/ComPWA/ampform/releases/tag/0.11.1)
> build: allow installing AmpForm v0.11.x

- .github/workflows/ci-style.yml
- .pre-commit-config.yaml
- README.md
- pyrightconfig.json
- tox.ini
See ComPWA/qrules#87
Note https://github.com/ComPWA/tensorwaves/pull/309#issuecomment-908152365. This comment is still relevant.
> ci!: switch to pre-commit.ci where possible

- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .github/workflows/requirements-cron.yml
- .github/workflows/requirements-pr.yml
- .pre-commit-config.yaml
- setup.cfg
Fixes https://github.com/ComPWA/tensorwaves/runs/4281696778#step:3:65
> ci: update pip constraints and pre-commit config

- src/tensorwaves/optimizer/callbacks.py
- src/tensorwaves/optimizer/minuit.py
- src/tensorwaves/optimizer/scipy.py
- tests/unit/optimizer/test_fit_simple_model.py
`CSVSummary` was writing `"estimator_type"` incorrectly (it was writing the optimizer type). This PR fixes that and adds the optimizer type as an additional entry, also to `YAMLSummary`.
> fix: write Optimizer and Estimator type

- setup.cfg
- src/tensorwaves/function/_backend.py
Should speed up [pre-commit job](https://github.com/ComPWA/tensorwaves/actions/workflows/ci-style.yml).
> build: reduce dependencies in style requirements

- src/tensorwaves/function/sympy.py
Fix-up to #374
Additional fixes:
* Enforce specifying `use_cse` argument in hidden functions.
* Remove `**kwargs` from lambdify functions. This helps mypy/pyright identify whether functions calls miss certain arguments.
> fix: forward use_cse arguments

- docs/abbreviate_signature.py
- docs/conf.py
- docs/install.md
- docs/usage/step3.ipynb
- setup.cfg
Preview here:
https://tensorwaves--381.org.readthedocs.build/en/381/install.html
[![image](https://user-images.githubusercontent.com/29308176/145199806-c583ab2d-cddb-4aca-aadf-c0ca1631c746.png)](https://tensorwaves--381.org.readthedocs.build/en/381/install.html)
Additional improvements:
- Check link anchors with [`linkcheck_anchors = True`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_anchors).
- Removed `typing-extensions` from requirements.
> docs: add GPU installation tips

- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- setup.cfg
lambdify doesn't work when sympy is to old
> build: set minimal dependencies sympy and pyyaml

- .cspell.json
- docs/usage.ipynb
- docs/usage/chi-squared.ipynb
- src/tensorwaves/estimator.py
- src/tensorwaves/interface.py
- tests/test_estimator.py
Also includes improvements to the documentation of `estimator` module.
> feat!: implement chi-squared estimator

- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .github/workflows/ci-docs.yml
- .pre-commit-config.yaml
- docs/amplitude-analysis.ipynb
- docs/amplitude-analysis/analytic-continuation.ipynb
- docs/conf.py
- docs/usage.ipynb
- docs/usage/basics.ipynb
- docs/usage/binned-fit.ipynb
- docs/usage/caching.ipynb
- docs/usage/chi-squared.ipynb
- docs/usage/faster-lambdify.ipynb
- docs/usage/unbinned-fit.ipynb
- setup.cfg
Closes https://github.com/ComPWA/repo-maintenance/issues/43
[![image](https://user-images.githubusercontent.com/29308176/149676020-8281cbb4-8cae-4e1a-a171-b451809ea993.png)](https://tensorwaves--400.org.readthedocs.build/en/400/usage.html)
> docs: add notebook button for Deepnote

- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .github/workflows/requirements-cron.yml
- .pre-commit-config.yaml
See https://github.com/ComPWA/repo-maintenance/pull/48
> fix: run upgrade cron job on even weeks only

- .github/workflows/requirements-cron.yml
- .pre-commit-config.yaml
- .pylintrc
- docs/_relink_references.py
- src/tensorwaves/function/__init__.py
- src/tensorwaves/interface.py
See [`import attrs`](https://hynek.me/articles/import-attrs/#the-last-step-import-attrs) and [`attrs` TNG](https://www.attrs.org/en/21.4.0/names.html#attrs-tng).
> chore: switch to new import attrs API

- .github/workflows/ci-docs.yml
- .github/workflows/ci-style.yml
- .github/workflows/ci-tests.yml
- .github/workflows/linkcheck.yml
- .gitpod.yml
- .pre-commit-config.yaml
- .vscode/extensions.json
- .vscode/settings.json
[![image](https://user-images.githubusercontent.com/29308176/155362608-11bc9605-2e57-4e04-9cd5-f85ed93bd58b.png)](https://github.com/ComPWA/tensorwaves/actions/workflows/ci-tests.yml)
> ci: run tests with specific dependency versions

- .github/workflows/benchmark.yml
- .github/workflows/redirect-gh-pages.yml
- docs/index.md
Closes https://github.com/ComPWA/policy/issues/514
> DX: host benchmark results on separate repository
